name = "potato-fan-club"
compatibility_date = "2025-04-18"
compatibility_flags = ["nodejs_compat"]
main = ".svelte-kit/cloudflare/_worker.js"

[assets]
binding = "ASSETS"
directory = ".svelte-kit/cloudflare"

[observability]
enabled = true

[vars]


[[d1_databases]]
binding = "DB"
database_name = "potato"
database_id = "d639b441-80d4-4caf-b06c-b592087310df"


[[env.production.r2_buckets]]
binding = "POTATO"
bucket_name = "potato"