name = "foursons-stack"
compatibility_date = "2025-04-18"
compatibility_flags = ["nodejs_compat"]
main = ".svelte-kit/cloudflare/_worker.js"

[assets]
binding = "ASSETS"
directory = ".svelte-kit/cloudflare"

[observability]
enabled = true

[vars]
KINDE_ISSUER_URL = "https://seobrothers.kinde.com"
KINDE_REDIRECT_URL = "https://foursons-stack.seobrothers.workers.dev/api/auth/kinde_callback"
KINDE_POST_LOGOUT_REDIRECT_URL = "https://foursons-stack.seobrothers.workers.dev/"
KINDE_POST_LOGIN_REDIRECT_URL = "https://foursons-stack.seobrothers.workers.dev/"
KINDE_SCOPE = "profile email offline openid"

[[d1_databases]]
binding = "DB"
database_name = "stack-demo-db"
database_id = "444dd48b-ce12-449b-acd5-675db52a83f2"
